config/routes.rb
TrackIt::Application.routes.draw do

  root 'static_pages#home'

  devise_for :users, :skip => [:sessions]

  resources :trackers, only: [:create, :destroy, :edit, :update]

  devise_scope :user do
    get 'signin' => 'devise/sessions#new', as: :new_user_session
    post 'signin' => 'devise/sessions#create', as: :user_session
    delete 'signout' => 'devise/sessions#destroy', as: :destroy_user_session
    get 'signup', to: 'devise/registrations#new'
  end

  get 'contact', to: 'static_pages#contact'
  get 'dashboard', to: 'static_pages#dashboard'
  get 'results', to: 'scraper#results'
  get 'bookmarklet', to: 'static_pages#bookmarklet'
  get 'help', to: 'static_pages#help'
  get 'addalert', to: 'static_pages#add_alert'
  get 'help', to: 'static_pages#help'
  get 'letter', to: 'static_pages#letter'

  

end

app/controllers/static_pages_controller.rb
require 'open-uri'
require 'open_uri_redirections'
require 'json'

class StaticPagesController < ApplicationController
  include ProductTrackerHelper
  include ApiHelper
  include DashboardHelper
  include ScraperHelper
  before_action :authenticate_user!, only: [:dashboard, :add_alert]

  def home
    if signed_in?
      redirect_to dashboard_path
    end
  end

  # TODO DONT FORGET THERES ANOTHER ONE
  def add_alert
    if params[:url]
      # redirect to scraper if we don't have an api for it
      temp_host = get_host(clean_url(params[:url]))
      if BLACKLIST.include? temp_host
        # TODO could be more customizable messages
        flash[:danger] = "Please Use a Shopping Website."
        redirect_to root_url
        return
      end

      temp_api = categorize_api(temp_host)
      if temp_api == "scrape" && !params[:xpath] && !params[:input_price]
        redirect_to results_path url: params[:url]
        return
      end

      @tracker = current_user.trackers.new(url: params[:url])
      if @tracker.save
        if @tracker.product.current_price == 1 || @tracker.product.current_price == 0
          flash[:danger] = "Sorry, we are unable to track your product at this time due to company policies."
          redirect_to dashboard_url
          return
        end
        redirect_to edit_tracker_path(@tracker, first_time: true)
      else
        # TODO could be more customizable messages
        logger.error "creation failed for bookmarklet with url: #{params[:url]}"
        flash[:danger] = "Sorry, we are unable to support this website at this time."
        redirect_to root_url
      end
    else
      flash[:danger] = "Sorry, please try using the bookmarklet again."
      redirect_to dashboard_path
    end
  end

  def help
  end

  def contact
  end

  def letter
  end

  def dashboard
    @tracker = Tracker.new
    @tracker_list = current_user.trackers
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def to_dollars(cents)
    cents = (cents.to_f)/100
    sprintf('%.2f', cents)
  end

  def full_name(user)
    "#{user.first_name} #{user.last_name}"
  end
end

app/views/static_pages/add_alert.html.erb
add_alert.html.erb

app/views/static_pages/bookmarklet.html.erb
<div class = "container">
  <div class = "row centered">
    <div class= "col-sm-4 col-sm-offset-4 centered">
      <h1>Bookmarklet for your Browser</h1>
      <hr>
      <div style="text-align:center">
        <a class="btn btn-primary" href="javascript:(function(){url = '<%= root_url %>addalert'+'?'+'url='+document.URL; window.open(url, '_blank');})();">Thriftster Bookmarklet</a>
      </div>
      <hr>
      <h3>1</h3>
      <p style="text-align:left">
        Just drag and drop the button above into your bookmarks or favorites bar. 
        <a id="attach_box">(Don't see a bookmarks bar?)</a>
      </p>
      <div id="sec_box" style="display: none;">
        <img class="center" width="300" src="https://dl.dropbox.com/s/iw5ubjxc816t8zp/bookmark_directions.png" alt="">
      </div>
      <hr>
      <h3>2</h3>
      <p style="text-align:left">
      When you come across a product you want on your favorite retail site, just click the bookmarklet to start tracking it.</p>
      <hr>
      <h3>3</h3>
      <p style="text-align:left">
        We'll send you an email when the products you want go on sale!
      </p>
      <hr>
      <div style="text-align:center">
        <a class="btn btn-primary" href="/">Back</a>
      </div>
      <hr>
    </div>
  </div>
</div>

app/views/static_pages/contact.html.erb
contact.html.erb

app/views/static_pages/dashboard.html.erb
<div class="alert alert-info" style="margin-bottom: 0;
text-align: center;">Please read <%= link_to "a letter from the developers", letter_path %>.</div>
<div class="jumbotron hero-spacer dashboard-form">
  <h1>Add a Price Alert</h1>
  <p style="text-align:center">Paste the URL of the product you want to track below and we'll notify you when it goes on sale.  Please be sure to use the url of the specific item page.
  </p>
  <%= bootstrap_form_for(@tracker) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.text_field :url, autofocus: true, hide_label: true %>
  <div class="form-submit">
    <%= f.submit "Start Tracking", class: "btn btn-outline-primary btn-outline-inverted center" %>
    <%= link_to "Confused?", help_path, class: "btn btn-outline-red btn-outline-inverted center", data: { :"no-turbolink" => "" } %>
  </div>
  <% end %>
</div>
<hr>
<div id="tracker-results">
  <div class="row">
    <h2>Your Tracked Items </h2>
    <div class="col-sm-offset-3 col-sm-6 center search-trackers">
      <input class="search form-control" placeholder="Search Your Alerts"></input>
    </div>
    <div class="col-sm-offset-3 col-sm-6 center search-trackers">
      <a class="sort btn btn-outline-primary col-sm-12 col-md-4 btn-outline-inverted center" data-sort="product-name">
        Sort by product name
      </a><!--
      --><a class="sort btn btn-outline-primary col-sm-12 col-md-4 btn-outline-inverted center" data-sort="price-orig">
        Sort by original price
      </a><!--
      --><a class="sort btn btn-outline-primary col-sm-12 col-md-4 btn-outline-inverted center" data-sort="price-current">
        Sort by current price
      </a>
    </div>
  </div>
  <div class="row col-xs-12">
    <ul class="list trackers">
      <% if @tracker_list.any? %>
      <%= render @tracker_list %>
      <% end %>
    </ul>
  </div>
</div>
<!-- /.row -->
<!-- /.row -->

<hr>

app/views/static_pages/help.html.erb
<!-- Featured Icons -->  
<div id="white">
  <div class="container">
    <div class="row mt">
      <div class="col-lg-4 col-lg-offset-4 centered">
        <h2>Three simple steps.</h2>
        <hr>
      </div>
    </div>
    <div class="row mt">
      <div class="col-lg-4">
        <p class="capitalize">1</p>
        <h4>Copy and Paste Your URL</h4>
        <p class="text-field">Shop your favorite retail sites. When you come across an item you want, copy and paste the URL of its product page into the Thriftster dashboard and hit 'start tracking'.  You can also use the Thriftster Bookmarklet for quick access.</p>
        <img class="gif-imgs" src="https://dl.dropbox.com/s/6jhpgfpgqap4wuj/directions1.gif">
      </div>
      <div class="col-lg-4">
        <p class="capitalize">2</p>
        <h4>Select Price</h4>
        <p class="text-field">We have an extensive listing of prices and we'll do our best to locate the price after you submit the URL.  Sometimes our server needs your help in locating the price on the page.  We'll prompt you if we need you to help us find the price!</p>
        <img class="gif-imgs" src="https://dl.dropbox.com/s/pazytppnkqyfq8b/directions2.gif">
      </div>
      <div class="col-lg-4">
        <p class="capitalize">3</p>
        <h4>Final Touches</h4>
        <p class="text-field">Feel free to edit the name of the object and customize when you want to be notified of a sale.  When we detect a price drop, we will email you.</p>
        <img class="gif-imgs" src="https://dl.dropbox.com/s/whzukwup0h8cslt/directions3.gif">
      </div>      
    </div><!-- /row -->
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 centered">
        <h5>Some urls work better than others.  Try adding a product from BestBuy or Amazon for example!</h5>
      </div>
      <div class="col-lg-6 col-lg-offset-3 centered">
        <hr>
        <h2>Please be sure to also leave us suggestions using our feedback form on the bottom right!</h2>
        <hr>
      </div>
    </div>
  </div><!-- /container -->
</div><!-- /white -->

app/views/static_pages/home.html.erb
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
<![endif]-->

<div class="alert alert-info" style="margin-bottom: 0;
text-align: center;">Please read <%= link_to "a letter from the developers", letter_path %>.</div>

<!-- HeaderWrap -->
<div id="headerwrap">
  <div class="dark-overlay"></div>
  <div class="container">
    <div class="row centered">
      <div class="col-lg-8 col-lg-offset-2 mt">
        <h1 class="animation slideDown">Never miss a sale again. We'll notify you when the products you want go on sale.</h1>
        <p class="mt"><%= link_to "GET STARTED", signup_path, class: "btn btn-cta btn-lg" %></p>
      </div>

    </div><!-- /row -->
  </div><!-- /container -->
</div> <!-- /headerwrap -->

<!-- Blog Posts -->   
<div class="container"> 

  <div class="row mt centered ">
    <div class="col-lg-4 col-lg-offset-4">
      <h3>How it works...</h3>
      <hr>
    </div>
  </div><!-- /row -->

  <div class="row mt centered">
    <div class="col-lg-4 col-md-4 col-xs-12 desc">
      <a class="b-link-fade b-animate-go" href="#"><%= image_tag "howitworks-01.png", width: "100%" %>
        <div class="b-wrapper">
          <h4 class="b-from-left b-animate b-delay03">Get</h4>
          <p class="b-from-right b-animate b-delay03">the bookmarklet.</p>
        </div>
      </a>
      <p>Get the bookmarklet</p>
      <p class="lead">Drag and drop our bookmarklet into your browser toolbar.</p>
      <hr-d>
    </div><!-- col-lg-4 -->

    <div class="col-lg-4 col-md-4 col-xs-12 desc">
      <a class="b-link-fade b-animate-go" href="#"><%= image_tag "howitworks-02.png", width: "100%" %>
        <div class="b-wrapper">
          <h4 class="b-from-left b-animate b-delay03">Shop</h4>
          <p class="b-from-right b-animate b-delay03">your favorite sites.</p>
        </div>
      </a>
      <p>Shop your favorite sites</p>
      <p class="lead">Just hit the bookmarklet button when you come across a product you want.</p>
      <hr-d>
    </div><!-- col-lg-4 -->

    <div class="col-lg-4 col-md-4 col-xs-12 desc">
      <a class="b-link-fade b-animate-go" href="#"><%= image_tag "howitworks-03.png", width: "100%" %>
        <div class="b-wrapper">
          <h4 class="b-from-left b-animate b-delay03">Save</h4>
          <p class="b-from-right b-animate b-delay03">when the price drops.</p>
        </div>
      </a>
      <p>That's it!</p>
      <p class="lead">We'll send you an email when the products you want go on sale.</p>
      <hr-d>
    </div><!-- col-lg-4 -->

  </div><!-- /row -->
</div>

<!-- Brands + Clients -->  
<div id="grey">
  <div class="container">
    <div class="row mt centered ">
      <div class="col-sm-4 col-sm-offset-4">
        <h3>Featured Retailers</h3>
        <hr>
      </div><!-- /col-lg-4 -->
    </div><!-- /row -->

    <div class="row centered">
      <!-- Begin first row -->
      <div class="col-sm-3 pt">
        <img class="img-responsive" src="http://img1.wikia.nocookie.net/__cb20100929014950/logopedia/images/c/cd/500px-Amazon_com_logo_svg.png" alt="">
      </div>
      <div class="col-sm-3 pt">
        <img class="img-responsive" src="http://michaelbox.net/wp-content/images/Target_old_logo.png" alt="">
      </div>
      <div class="col-sm-3 pt">
        <img class="img-responsive" src="http://img2.wikia.nocookie.net/__cb20130113164539/walmart/images/9/92/Walmart_logo.png" alt="">
      </div>
      <div class="col-sm-3 pt">
        <img class="img-responsive" src="http://upload.wikimedia.org/wikipedia/commons/4/48/EBay_logo.png" alt="">
      </div>
      <!-- End first row -->

      <!-- Begin second row -->
      <div class="col-sm-3 pt">
        <img class="img-responsive" src="http://img3.wikia.nocookie.net/__cb20100920050450/logopedia/images/4/4d/Macy%27s.png" alt="">
      </div>
      <div class="col-sm-3 pt">
        <img class="img-responsive" src="http://www.maximumpc.com/files/newegg_411.png" alt="">
      </div>
      <div class="col-sm-3 pt">
        <%= image_tag "hmlogo.png", class: "img-responsive" %>
      </div>      
      <div class="col-sm-3 pt">
        <h3>...and hundreds more</h3>
      </div>
      <!-- End second row -->

    </div><!-- /row -->
  </div><!-- /container -->
</div><!-- /grey -->

<!-- Featured Icons -->  
<div id="white">
  <div class="container">
    <div class="row mt">
      <div class="col-lg-4 col-lg-offset-4 centered">
        <h3>How it works...</h3>
        <hr>
      </div>
    </div>
    <div class="row mt">
      <div class="col-lg-4">
        <p class="capitalize">1</p>
        <h4>Get the bookmarklet</h4>
        <p>Drag and drop the bookmarklet into your browser toolbar.</p>
      </div>
      <div class="col-lg-4">
        <p class="capitalize">2</p>
        <h4>Shop your favorite sites</h4>
        <p>Just hit the bookmarklet button when you come across a product you want.</p>
      </div>
      <div class="col-lg-4">
        <p class="capitalize">3</p>
        <h4>That's it!</h4>
        <p>We'll send you an email when the products you want go on sale.</p>
      </div>      
    </div><!-- /row -->
  </div><!-- /container -->
</div><!-- /white -->





<script>
$(window).scroll(function() {
  $('.si').each(function(){
    var imagePos = $(this).offset().top;

    var topOfWindow = $(window).scrollTop();
    if (imagePos < topOfWindow+400) {
      $(this).addClass("slideUp");
    }
  });
});
</script>    

app/views/static_pages/letter.html.erb
<div class="row">
  <h1>Thank You</h1>
</div>
<div class="row">
  <div class="col-md-offset-3 col-md-6">
    <p class="letter-heading">
      <% if signed_in? %>
      Dear <%= current_user.first_name %>,
      <% else %>
      Dear Friends,
      <% end %>
    </p>
    <p class="letter-paragraph">
      Haley and I released Thriftster as part of our Private Beta to around 75 people.  In a day, we have grow to <b>hundreds of products</b> being actively tracked and <b>nearly 15%</b> of them have dropped in price since.  In 24 hours, Thriftster has tracked savings of nearly <b>a thousand dollars</b>.
    </p>
    <p class="letter-paragraph">
      All thanks to you, the user.  From the beginning, the user, not us, has been driving the development of Thriftster.  Features that you request are the ones that are put up.  The feedback in the past week have been overwhelming.  With your help, we have uncovered numerous bugs and potential features that we would have never thought of.
    </p>
    <p class="letter-paragraph">
      With the current amount of schoolwork that we both have, Haley and I will unfortunately not be able to monitor the beta development until futher notice.  However, please continue to use our site.  Feedback and bug reports are always welcomed.  
    </p>
    <p class="letter-paragraph">
      We will have some awesome features and next steps in store for the future.  Thank you for all of your support and get excited for updates! 
    </p>
    <p class="letter-closing">
      Sincerely,
      <br>
      Irvin and Haley
    </p>
  </div>
</div>