config/routes.rb
TrackIt::Application.routes.draw do

  root 'static_pages#home'

  devise_for :users, :skip => [:sessions]

  resources :trackers, only: [:create, :destroy, :edit, :update]

  devise_scope :user do
    get 'signin' => 'devise/sessions#new', as: :new_user_session
    post 'signin' => 'devise/sessions#create', as: :user_session
    delete 'signout' => 'devise/sessions#destroy', as: :destroy_user_session
    get 'signup', to: 'devise/registrations#new'
  end

  get 'contact', to: 'static_pages#contact'
  get 'dashboard', to: 'static_pages#dashboard'
  get 'results', to: 'scraper#results'
  get 'bookmarklet', to: 'static_pages#bookmarklet'
  get 'help', to: 'static_pages#help'
  get 'addalert', to: 'static_pages#add_alert'
  get 'help', to: 'static_pages#help'
  get 'letter', to: 'static_pages#letter'

  

end

app/views/layouts/_feedback_form.html.erb
<iframe name="hidden_iframe" id="hidden_iframe"
style="display:none;" onload="if(submitted)
{feedbackFormSubmitted();}"></iframe>
<form action="https://docs.google.com/a/princeton.edu/forms/d/1wk6hP5wbe9TbIV7lLKjiddU8NoRwGhfMxykg44bQdvk/formResponse" method="POST" id="ss-form" target="hidden_iframe" onsubmit="submitted=true;">
  <ol role="list" class="ss-question-list" style="padding-left: 0">
    <div class="ss-form-question errorbox-good" role="listitem" style="display:none;">
      <div dir="ltr" class="ss-item  ss-text">
        <div class="ss-form-entry">
          <label class="ss-q-item-label" for="entry_615349471">
            <div class="ss-q-title">Name
            </div>
            <div class="ss-q-help ss-secondary-text" dir="ltr"></div>
          </label>
          <input type="text" name="entry.615349471" value='<%= "#{full_name(current_user)} (#{current_user.email})" %>' class="ss-q-short" id="entry_615349471" dir="auto" aria-label="Name  " title="">
        </div>
      </div>
    </div> 
    <div class="ss-form-question errorbox-good" role="listitem">
      <div dir="ltr" class="ss-item  ss-paragraph-text">
        <div class="ss-form-entry">
          <label class="ss-q-item-label" for="entry_1958558838">
            <div class="ss-q-title">What features/pages of this site are difficult to use?
            </div>
            <div class="ss-q-help ss-secondary-text" dir="ltr">
            </div>
          </label>
          <textarea name="entry.1958558838" rows="8" cols="0" class="ss-q-long" id="entry_1958558838" dir="auto" aria-label="What were the favorite parts of your site?  "></textarea>
        </div>
      </div>
    </div>
    <div class="ss-form-question errorbox-good" role="listitem">
      <div dir="ltr" class="ss-item  ss-paragraph-text">
        <div class="ss-form-entry">
          <label class="ss-q-item-label" for="entry_1275235833">
            <div class="ss-q-title">What features would you like to see added?
            </div>
            <div class="ss-q-help ss-secondary-text" dir="ltr"></div>
          </label>
          <textarea name="entry.1275235833" rows="8" cols="0" class="ss-q-long" id="entry_1275235833" dir="auto" aria-label="How can we improve Thriftster?  "></textarea>
        </div>
      </div>
    </div>
    <div class="ss-form-question errorbox-good" role="listitem">
      <div dir="ltr" class="ss-item  ss-paragraph-text">
        <div class="ss-form-entry">
          <label class="ss-q-item-label" for="entry_837466983">
            <div class="ss-q-title">Additional suggestions/comments/questions?
            </div>
            <div class="ss-q-help ss-secondary-text" dir="ltr"></div>
          </label>
          <textarea name="entry.837466983" rows="8" cols="0" class="ss-q-long" id="entry_837466983" dir="auto" aria-label="Additional Questions/Comments?  "></textarea>
        </div>
      </div>
    </div>
    <input type="hidden" name="draftResponse" value="[,,&quot;4454179487231552457&quot;]
    ">
    <input type="hidden" name="pageHistory" value="0">
    <input type="hidden" name="fbzx" value="4454179487231552457">
    <input type="submit" name="submit" value="Submit" class="btn btn-default" id="ss-submit">
    <button class="btn btn-default" disabled=true id="ss-submit-disabled">Submitting, please wait...</button>
  </ol>
</form>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <p class="muted credits">
      Copyright 2014.
    </p>
  </div>
</div>

<% if signed_in? %>
<div id="feedback-form">
  <a id="feedback-button">Tell us what you think.</a>
  <div class="form">
    <%= render "layouts/feedback_form" %>
  </div>
</div>
<% end %>

app/views/layouts/_header.html.erb
<div class="color-bar">
</div>
<div class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" data-no-turbolink="" href="<%= root_url %>">Thriftster<sub class="private-beta">Private BETA</sub></a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Welcome, <%= current_user.first_name %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "My Account", edit_user_registration_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
          </ul>
        </li>
        <% end %> 
        <!-- Is this still needed? -->
      </ul>
      <div class="pull-right">

      <%= link_to "Get the Bookmarklet", bookmarklet_path, class: "btn btn-primary navbar-btn" %>
      <% if signed_in? %>
        <%= link_to "Need Help?", help_path, class: "btn btn-default navbar-btn", data: { :"no-turbolink" => "" } %>
      <% else %>
        <%= link_to "Sign in", new_user_session_path, class: "btn btn-primary navbar-btn" %>
        <%= link_to "Sign up", signup_path, class: "btn btn-default navbar-btn" %>
      <% end %>
    </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thriftster</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    params[:controller], media: "all" %>
  <%= javascript_include_tag params[:controller] %>

  <% if custom_css_page? %>
  <%= javascript_include_tag 'home' %>
  <%= stylesheet_link_tag 'home' %>
  <% end %>

  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="google-site-verification" content="gNoYxkAvNEu18sUpJ3z-YlGDUGGAPEoBJzbIK_gmawg" />
  <meta name="og:image" content="<%= asset_path 'logoT.png' %>">
  <meta name="og:title" content="Thriftster - Price Alerts for Your Items">
  <meta property="og:site_name" content="Thriftster"/>
  <meta property="og:type" content="website" />
  <meta name="description" property="og:description" content="Thriftster offers free price alerts for your favorite products.  Simply provide us an url of the product and we will email you when it goes on sale." />
</head>

<% if custom_css_page? %>
<body data-no-turbolink>
<% end %>
  
  
<div id="main-wrapper">
  <%= render 'layouts/header' %>

  <% unless custom_css_page? %>
    <div class="container">
  <% end %>

    <% flash.each do |key, value| %>
      <% if key.to_s == "notice" %>
        <div class="alert alert-<%= key %> alert-success"><%= value %></div>
      <% elsif key.to_s == "alert" %>
        <div class="alert alert-<%= key %> alert-danger"><%= value %></div>
      <% else %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    <% end %>
    <%= yield %>

  <% unless custom_css_page? %>
    </div>
  <% end %>
</div>
  <%= render 'layouts/footer' %>

</body>
</html>